goog.provide('fu.style');

goog.require('fu.env.client');
goog.require('goog.asserts');
goog.require('goog.dom.DomHelper');
goog.require('goog.math.Coordinate');


/**
 * @param {Element} element
 * @param {number} x
 * @param {number} y
 */
fu.style.setTranslate3d = function(element, x, y) {
  goog.asserts.assert(fu.env.client.USE_WEBKIT_CSS3D);
  element.style['webkitTransform'] =
    'translate3d(' + x + 'px,' + y + 'px,0)';
};


/**
 * @param {Element} element
 * @param {number} duration
 */
fu.style.setTransformTransition = function(element, duration) {
  goog.asserts.assert(fu.env.client.USE_WEBKIT_TRANSITION);
  // The values of cubic-bezier(*) is generated by
  // http://matthewlein.com/ceaser/ which gives us natural-enough animation.
  element.style['webkitTransition'] = '-webkit-transform ' +
    Math.round(duration) + 'ms cubic-bezier(0, 0.02, 0.055, 1)';
};


/**
 * @param {Element} element
 */
fu.style.removeTransition = function(element) {
  goog.asserts.assert(fu.env.client.USE_WEBKIT_TRANSITION);
  // The values of cubic-bezier(*) is generated by
  // http://matthewlein.com/ceaser/ which gives us natural-enough animation.
  element.style['webkitTransition'] = '';
};


/**
 * @param {Element} element
 * @return {goog.math.Coordinate}
 */
fu.style.getTranslatePosition = function(element) {
  var doc = goog.dom.getOwnerDocument(element);
  var dom = new goog.dom.DomHelper(doc);
  var win = dom.getWindow();
  var style = doc.defaultView.getComputedStyle(element, null);
  var CSSMatrix = /** @type {Function} */ (win['WebKitCSSMatrix']);
  var transform = new CSSMatrix(style['webkitTransform']);
  var x = parseFloat(transform['m41']);
  var y = parseFloat(transform['m42']);
  return new goog.math.Coordinate(x, y);
};